name: File Storage CI

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

defaults:
  run:
    working-directory: ./fileStorage
    
jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [17.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  test-coverage:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    needs: build

    steps:
      - name: Checking out github project
        uses: actions/checkout@v3
      
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Dependencies
        run: npm ci

      - name: Test and verify application
        run: |
          npm ci
          CI=true npm run test